name: dependency_injection
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #LocalDeps
  common_dependency: ^0.0.1
  master_data: ^0.0.1
  home: ^0.0.1
  navigation: ^0.0.1
  #RemoteDeps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
