name: master_data
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  common_dependency: ^0.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.0
  freezed: ^2.1.1
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
