include: package:flutter_lints/flutter.yaml

linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # false positive when using Freezed
    invalid_annotation_target: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
