name: home
description: A new Flutter package project.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #LocalDeps
  common_dependency: ^0.0.1
  #RemoteDeps
  email_validator: ^2.1.17
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  firebase_storage: ^12.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.0
  freezed: ^2.1.1
  bloc_test: ^9.1.0

flutter:
